crate_name = "async-trait"
version = "0.1.48"
reviewed-by-team = "Android Legacy"

[common]
code_is_not_malicious = true
maintainable_code = 2
good_api = true
good_docs = true
build_script = true
proc_macro = true
