crate_name = "grpcio-sys"
version = "0.9.1+1.38.0"
reviewed-by-team = "Android Legacy"

[common]
code_is_not_malicious = true
maintainable_code = 2
good_api = true
good_docs = true
build_script = true
