crate_name = "inotify"
version = "0.9.3"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
maintainable_code = 2
good_docs = true
testing_status = 2
reasonably_maintained = true
has_unsafe_code = true
