crate_name = "link-cplusplus"
version = "1.0.5"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
good_docs = true
build_script = true

[common.build_script_details]
deterministic = true

[common.build_script_details.purpose]
codegen = false
cfg_algebra = true
links_libs = [ "stdc++", "c++",]
builds_libs = []
misc = false
