crate_name = "proc-macro-hack"
version = "0.5.19"
reviewed-by-team = "Android Legacy"

[common]
code_is_not_malicious = true
maintainable_code = 2
good_api = true
good_docs = true
build_script = true
proc_macro = true
