crate_name = "proc-macro-nested"
version = "0.1.7"
reviewed-by-team = "Android Legacy"

[common]
code_is_not_malicious = true
maintainable_code = 2
good_api = true
good_docs = true
build_script = true
