crate_name = "radium"
version = "0.5.3"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
maintainable_code = 2
good_docs = true
has_unsafe_code = false
build_script = true

[common.build_script_details]
deterministic = true

[common.build_script_details.purpose]
codegen = false
cfg_algebra = true
links_libs = []
builds_libs = []
misc = false
